image:
  repository: buildbrain/project-service
  tag: latest
port: 5000
replicaCount: 1
env:
  config:
    MONGO_URL: mongodb://mongo:27017
    MONGO_DB: buildbrain
  secret:
    MONGO_USER: ""
    MONGO_PASS: ""

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
